In [1]:
import matplotlib.pyplot as plt
from PIL import Image
import numpy as np

#### **Reading an Image to a NumPy Array with Matplotlib**

In [2]:
img_array_1 = plt.imread('Boston-Terrier.jpg')
print(img_array_1)

[[[ 80 111  44]
  [ 80 112  45]
  [ 80 112  45]
  ...
  [ 92 118  55]
  [ 91 117  54]
  [ 90 116  53]]

 [[ 80 111  44]
  [ 80 112  45]
  [ 81 113  46]
  ...
  [ 92 118  55]
  [ 91 117  54]
  [ 91 117  54]]

 [[ 80 111  44]
  [ 81 113  46]
  [ 81 113  46]
  ...
  [ 93 117  55]
  [ 93 117  55]
  [ 92 116  54]]

 ...

 [[ 71  99  38]
  [ 72 100  39]
  [ 72 102  38]
  ...
  [ 69 102  31]
  [ 66  99  30]
  [ 64  96  29]]

 [[ 75 103  42]
  [ 76 105  41]
  [ 76 107  40]
  ...
  [ 70 101  31]
  [ 67  98  30]
  [ 66  97  30]]

 [[ 74 104  40]
  [ 75 105  41]
  [ 76 107  40]
  ...
  [ 69 100  30]
  [ 67  98  30]
  [ 66  96  32]]]


#### **Reading an Image to a NumPy Array with Pillow**

In [ ]:
img_pil = Image.open('Boston-Terrier.jpg')
img_array_2 = np.array(img_pil)
print(img_array_2)

NameError: name 'img_array_2' is not defined

# **References and Additional Learning**

## **Documentation**

- **[pandas.DataFrame.sample](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sample.html) from pandas.pydata.org**

# **Connect**
- **Feel free to connect with Adrian on [YouTube](https://www.youtube.com/channel/UCPuDxI3xb_ryUUMfkm0jsRA), [LinkedIn](https://www.linkedin.com/in/adrian-dolinay-frm-96a289106/), [X](https://twitter.com/DolinayG), [GitHub](https://github.com/ad17171717), [Medium](https://adriandolinay.medium.com/) and [Odysee](https://odysee.com/@adriandolinay:0). Happy coding!**

# **Podcast**

- **Check out Adrian's Podcast, The Aspiring STEM Geek on [YouTube](https://www.youtube.com/@AdrianDolinay/podcasts), [Spotify](https://open.spotify.com/show/60dPNJbDPaPw7ru8g5btxV), [Apple Podcasts](https://podcasts.apple.com/us/podcast/the-aspiring-stem-geek/id1765996824), [Audible](https://www.audible.com/podcast/The-Aspiring-STEM-Geek/B0DC73S9SN?eac_link=MCFKvkxuqKYU&ref=web_search_eac_asin_1&eac_selected_type=asin&eac_selected=B0DC73S9SN&qid=IrZ84nGqvz&eac_id=141-8769271-5781515_IrZ84nGqvz&sr=1-1) and [iHeart Radio](https://www.iheart.com/podcast/269-the-aspiring-stem-geek-202676097/)!**